version: '3'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: employee_management_system   
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
     - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
     - backendNetwork
     
  spring-boot-ems:
    image: 172.27.59.80:8082/astha-github-actions/spring_app:1.0
    container_name: spring-boot-ems
    ports:
      - 8085:8080
    depends_on:
      - database
    networks:
      - backendNetwork
      - frontendNetwork
      
  angular:
    image: 172.27.59.80:8082/astha-github-actions/angular_app:1.0
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - spring-boot-ems
    networks:
      - frontendNetwork


volumes:
  dockerAngularSpringDatabaseData:
  
networks:
  backendNetwork:
  frontendNetwork:
