# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: |
            cd angular 
            npm install
            npm run build

    - run:  | 
             cd angular
             docker build -t 172.27.59.80:8082/astha-github-actions/angular_app:1.0 .
             docker login -u admin -p Cybage@123 http://172.27.59.80:8082
             docker push 172.27.59.80:8082/astha-github-actions/angular_app:1.0
 
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '11'
    - run: |
            cd spring-boot-ems
            mvn clean install
             
    
